### ISSUE TITLE
[Todo] 8/20~8/21

### ISSUE THREAD

**Issue by heerucan** [heerucan/iOS-Begin-Again#13]
#### 🥳 TIL 정리
- [ ] 클로저 데이터 전달 정리
- [x] 제네릭 정리
- [x] loadView 정리
- [x] init() 정리
- [x] BaseView, BaseViewController 정리
- [ ] 타입캐스팅 읽고 정리

#### 🥳 과제
- [x] TMDB에 제네릭 적용해서 리팩 (화면전환 코드)
- [ ] TMDB에 영화관 찾는 기능 추가
- [ ] TMDB 온보딩 UI 좀 더 업데이트하자
- [x] 클로저 값전달 연습 (어떤 프로젝트든 한 번 이상 해보자)
- [ ] 날씨앱 업데이트 - 지도 상에 핀 찍으면 해당 날씨를 가져오는 것으로 기능 추가
- [x] 날씨앱 리팩토링
- [x] Diary App 만들기 - BaseView, CustomView, BaseViewController, Type Casting, Generic, Closure 전달 활용해보기

#### 🥳 개인
- [x] CS 1강 듣고 정리
- [x] 스위프트 알고리즘 1문제
- [x] 스위프트 알고리즘 1문제
- [x] 스위프트 알고리즘 1문제
- [x] GCD weak self
- [x] 왈 끝내 조져.
